version: "3"

services:

  shopware:
    image: dockware/dev:latest
    container_name: shopware
    ports:
      - "17320:80"
      - "17321:22"
      - "17322:443"
      - "17323:8888"
      - "17324:9998"
      - "17325:9999"
      - "17326:3306"
    volumes:
      - "./:/var/www/html/custom/plugins/"
      - "/var/www/html/custom/plugins/bin"
      - "/var/www/html/custom/plugins/dist"
    environment:
      - XDEBUG_ENABLED=1
      - PHP_VERSION=8.1

volumes:
  shop_volume:
    driver: local
  web:
    external: false